### ISSUE TITLE
URL Parameters in OpenAPI spec sorted alphabetically instead of by appearance

### ISSUE THREAD

**Issue by noheton** [noheton/shepard#167]
***In GitLab by @xit-paul-reinhardt on Aug 19, 2024, 16:10 GMT+2:***

# Bug Report

## :bug: Summary

The URL parameters in the OpenAPI spec are listed alphabetically now instead of by appearance. For example in the old OpenAPI spec the parameters of  `/structureddatas/{structureddataContainerId}/payload/{oid}` where:

```yaml
  parameters:
    - name: structureddataContainerId
      in: path
      required: true
      schema:
        type: integer
        format: int64
    - name: oid
      in: path
      required: true
      schema:
        type: string
```

where in the new OpenAPI spec it's:

```yaml
  parameters:
    - name: oid
      in: path
      required: true
      schema:
        type: string    
    - name: structureddataContainerId
      in: path
      required: true
      schema:
        type: integer
        format: int64
```

## :bulb: Hints

* [https://stackoverflow.com/questions/77786738/quarkus-openapi-specification-parameter-is-alphabetically-ordered](https://stackoverflow.com/questions/77786738/quarkus-openapi-specification-parameter-is-alphabetically-ordered "https://stackoverflow.com/questions/77786738/quarkus-openapi-specification-parameter-is-alphabetically-ordered")
* [https://redirect.github.com/quarkusio/quarkus/issues/38736](https://redirect.github.com/quarkusio/quarkus/issues/38736 "https://redirect.github.com/quarkusio/quarkus/issues/38736")

## :thinking: Risks & Open Questions

**Assignees:** xit-paul-reinhardt

*Migrated from GitLab: https://gitlab.com/dlr-shepard/shepard/-/work_items/167*
